package com.example.eyetracking.data

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class EyeTrackingDataDto(
    @SerialName("sno")
    val sno: Int? = null,
    @SerialName("user_id")
    val userId: Int? = null, // Auto-generated by database
    @SerialName("age")
    val age: Int,
    @SerialName("gender")
    val gender: String,
    @SerialName("gaze_duration")
    val gazeDuration: Double,
    @SerialName("dwell_time")
    val dwellTime: Double,
    @SerialName("saccade_length")
    val saccadeLength: Double,
    @SerialName("distractor_saccades")
    val distractorSaccades: Int,
    @SerialName("fixation_count")
    val fixationCount: Int,
    @SerialName("refixation_ratio")
    val refixationRatio: Double,
    @SerialName("session_timestamp")
    val sessionTimestamp: String? = null,
    @SerialName("device_info")
    val deviceInfo: String? = null,
    @SerialName("calibration_quality")
    val calibrationQuality: Double? = null,
    @SerialName("created_at")
    val createdAt: String? = null,
    @SerialName("updated_at")
    val updatedAt: String? = null
)

data class EyeTrackingData(
    val sno: Int? = null,
    val userId: Int? = null, // Will be auto-assigned by database
    val age: Int,
    val gender: String,
    val gazeDuration: Double,
    val dwellTime: Double,
    val saccadeLength: Double,
    val distractorSaccades: Int,
    val fixationCount: Int,
    val refixationRatio: Double,
    val sessionTimestamp: String? = null,
    val deviceInfo: String? = null,
    val calibrationQuality: Double? = null
)

data class UserDetails(
    val age: Int,
    val gender: String,
    val userId: Int? = null // Auto-assigned when data is saved
)
